import{a as b,S as L,i as c}from"./assets/vendor-BsCdK5bc.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const p of s.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&n(p)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const v="https://pixabay.com/api/";async function g(r){try{return(await b.get(v,r)).data}catch(t){throw t}}function y(r){const t=document.querySelector(".gallery"),o=r.map(e=>`<li class="item-ul">
  <a href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}" /></a>
  <div class="about-img-div">
    <p class="description-img">Likes</p>
    <p class="description-img">Views</p>
    <p class="description-img">Comments</p>
    <p class="description-img">Downloads</p>
    <span class="description-value">${e.likes}</span>
    <span class="description-value">${e.views}</span>
    <span class="description-value">${e.comments}</span>
    <span class="description-value">${e.downloads}</span>
  </div>
</li>`).join("");t.insertAdjacentHTML("beforeend",o),new L(".gallery li a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()}const u=document.querySelector(".form"),i=document.querySelector(".loader"),w=document.querySelector(".gallery"),a=document.querySelector(".load-more-button"),h="47286025-dcd3f7c6d98bacb5edade47ee";let d=1,l="",m=0,f=0;u.addEventListener("submit",q);a.addEventListener("click",C);async function q(r){if(r.preventDefault(),l=u.elements.input.value.trim(),d=1,w.innerHTML="",l===""||l.length<2){c.error({position:"topRight",backgroundColor:"#ef4040",messageColor:"#fafafb",titleColor:"#fafafb",iconColor:"#fafafb",title:"",message:"The input field is empty or has less than two characters!"}),a.style.display="none";return}i.classList.remove("hidden");const t={params:{key:h,q:l,image_type:"photo",orientation:"horizontal",page:d,per_page:15}};try{const o=await g(t);i.classList.add("hidden"),o.hits.length===0?(c.error({position:"topRight",backgroundColor:"#ef4040",messageColor:"#fafafb",titleColor:"#fafafb",iconColor:"#fafafb",title:"",message:"No pictures found! Try again!"}),a.style.display="none"):(y(o.hits),a.classList.remove("hidden"),m=o.totalHits,f=Math.ceil(m/15),f>1?a.style.display="block":a.style.display="none")}catch(o){i.classList.add("hidden"),c.error({title:"",message:`Error fetching images: ${o.message||o}`})}finally{u.reset()}}async function C(){i.classList.remove("hidden"),d+=1;const r={params:{key:h,q:l,image_type:"photo",orientation:"horizontal",page:d,per_page:15}};try{const t=await g(r);i.classList.add("hidden"),y(t.hits);const n=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:n.height*2,behavior:"smooth"})}catch(t){i.classList.add("hidden"),c.error({title:"",message:`Error fetching images: ${t.message||t}`})}finally{d>=f&&(a.style.display="none",c.info({title:"",message:"We're sorry, but you've reached the end of search results."}))}}
//# sourceMappingURL=index.js.map
