import{a as b,S as L,i as l}from"./assets/vendor-BsCdK5bc.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const p of r.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&o(p)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const v="https://pixabay.com/api/";async function g(a){try{return(await b.get(v,a)).data}catch(e){throw e}}const w=new L(".gallery li a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250});function y(a){const e=document.querySelector(".gallery"),s=a.map(o=>`<li class="item-ul">
  <a href="${o.largeImageURL}"><img src="${o.webformatURL}" alt="${o.tags}" /></a>
  <div class="about-img-div">
    <p class="description-img">Likes</p>
    <p class="description-img">Views</p>
    <p class="description-img">Comments</p>
    <p class="description-img">Downloads</p>
    <span class="description-value">${o.likes}</span>
    <span class="description-value">${o.views}</span>
    <span class="description-value">${o.comments}</span>
    <span class="description-value">${o.downloads}</span>
  </div>
</li>`).join("");e.insertAdjacentHTML("beforeend",s),w.refresh()}const u=document.querySelector(".form"),d=document.querySelector(".loader"),q=document.querySelector(".gallery"),i=document.querySelector(".load-more-button"),h="47286025-dcd3f7c6d98bacb5edade47ee";let c=1,n="",m=0,f=0;u.addEventListener("submit",C);i.addEventListener("click",S);async function C(a){if(a.preventDefault(),n=u.elements.input.value.trim(),c=1,q.innerHTML="",n===""||n.length<2){l.error({position:"topRight",backgroundColor:"#ef4040",messageColor:"#fafafb",titleColor:"#fafafb",iconColor:"#fafafb",title:"",message:"The input field is empty or has less than two characters!"}),i.style.display="none";return}d.classList.remove("hidden");const e={params:{key:h,q:n,image_type:"photo",orientation:"horizontal",page:c,per_page:15}};try{const s=await g(e);s.hits.length===0?(l.error({position:"topRight",backgroundColor:"#ef4040",messageColor:"#fafafb",titleColor:"#fafafb",iconColor:"#fafafb",title:"",message:"No pictures found! Try again!"}),i.style.display="none"):(y(s.hits),i.classList.remove("hidden"),m=s.totalHits,f=Math.ceil(m/15),f>1?i.style.display="block":i.style.display="none")}catch(s){l.error({title:"",message:`Error fetching images: ${s.message||s}`})}finally{d.classList.add("hidden"),u.reset()}}async function S(){d.classList.remove("hidden"),c+=1;const a={params:{key:h,q:n,image_type:"photo",orientation:"horizontal",page:c,per_page:15}};try{const e=await g(a);y(e.hits);const o=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:o.height*2,behavior:"smooth"})}catch(e){l.error({title:"",message:`Error fetching images: ${e.message||e}`})}finally{d.classList.add("hidden"),c>=f&&(i.style.display="none",l.info({title:"",message:"We're sorry, but you've reached the end of search results."}))}}
//# sourceMappingURL=index.js.map
