import{a as b,S as L,i as c}from"./assets/vendor-BsCdK5bc.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const p of r.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&o(p)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const v="https://pixabay.com/api/";async function y(a){try{return(await b.get(v,a)).data}catch(e){throw e}}const w=new L(".gallery li a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250});function g(a){const e=document.querySelector(".gallery"),s=a.map(o=>`<li class="item-ul">
  <a href="${o.largeImageURL}"><img src="${o.webformatURL}" alt="${o.tags}" /></a>
  <div class="about-img-div">
    <p class="description-img">Likes</p>
    <p class="description-img">Views</p>
    <p class="description-img">Comments</p>
    <p class="description-img">Downloads</p>
    <span class="description-value">${o.likes}</span>
    <span class="description-value">${o.views}</span>
    <span class="description-value">${o.comments}</span>
    <span class="description-value">${o.downloads}</span>
  </div>
</li>`).join("");e.insertAdjacentHTML("beforeend",s),w.refresh()}const u=document.querySelector(".form"),i=document.querySelector(".loader"),q=document.querySelector(".gallery"),n=document.querySelector(".load-more-button"),h="47286025-dcd3f7c6d98bacb5edade47ee";let d=1,l="",m=0,f=0;u.addEventListener("submit",C);n.addEventListener("click",S);async function C(a){if(a.preventDefault(),l=u.elements.input.value.trim(),d=1,q.innerHTML="",l===""||l.length<2){c.error({position:"topRight",backgroundColor:"#ef4040",messageColor:"#fafafb",titleColor:"#fafafb",iconColor:"#fafafb",title:"",message:"The input field is empty or has less than two characters!"}),n.style.display="none";return}i.classList.remove("hidden"),i.style.display="block";const e={params:{key:h,q:l,image_type:"photo",orientation:"horizontal",page:d,per_page:15}};try{const s=await y(e);s.hits.length===0?(c.error({position:"topRight",backgroundColor:"#ef4040",messageColor:"#fafafb",titleColor:"#fafafb",iconColor:"#fafafb",title:"",message:"No pictures found! Try again!"}),n.style.display="none"):(g(s.hits),n.classList.remove("hidden"),m=s.totalHits,f=Math.ceil(m/15),f>1?n.style.display="block":n.style.display="none")}catch(s){c.error({title:"",message:`Error fetching images: ${s.message||s}`})}finally{i.classList.add("hidden"),i.style.display="none",u.reset()}}async function S(){i.classList.remove("hidden"),i.style.display="block",d+=1;const a={params:{key:h,q:l,image_type:"photo",orientation:"horizontal",page:d,per_page:15}};try{const e=await y(a);g(e.hits);const o=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:o.height*2,behavior:"smooth"})}catch(e){c.error({title:"",message:`Error fetching images: ${e.message||e}`})}finally{i.classList.add("hidden"),i.style.display="none",d>=f&&(n.style.display="none",c.info({title:"",message:"We're sorry, but you've reached the end of search results."}))}}
//# sourceMappingURL=index.js.map
